# Generated by Django 3.1.2 on 2020-11-01 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this artist', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this artist', primary_key=True, serialize=False),
        ),
    ]
