# Generated by Django 3.1.2 on 2020-11-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_core', '0002_auto_20201031_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='abbr',
            field=models.CharField(help_text='Abbreviation of breed name', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(help_text='Name of breed', max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(help_text='Breed of dog', on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='dogs_core.breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='is_neutered',
            field=models.BooleanField(default=False, help_text='Whether dog is neutered'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(help_text='Name of dog', max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], help_text='Sex of dog (m or f)', max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(help_text='Approximate weight of dog in pounds'),
        ),
    ]
