# Generated by Django 3.1.2 on 2020-11-01 02:02

from django.db import migrations

def make_abbreviation(name):
    words = name.split()
    if len(words) == 1:
        return words[0][:2].upper()
    else:
        return ''.join(w[0] for w in words).upper()


def populate_abbreviations(apps, schema_editor):
    Breed = apps.get_model('dogs_core', 'Breed')
    for breed in Breed.objects.all():
        breed.abbr = make_abbreviation(breed.name)
        breed.save()

class Migration(migrations.Migration):


    dependencies = [
        ('dogs_core', '0003_auto_20201031_2040'),
    ]

    operations = [
        migrations.RunPython(populate_abbreviations)
    ]
