# Generated by Django 3.1.2 on 2020-11-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_core', '0004_auto_20201031_2202'),
    ]

    operations = [
    ]
