# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import superheroes.models


class Migration(migrations.Migration):

    replaces = [('superheroes', '0001_initial'), ('superheroes', '0002_auto_20171102_0712'), ('superheroes', '0003_superhero_date_of_death'), ('superheroes', '0004_auto_20171116_0921')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('real_name', models.CharField(max_length=32)),
                ('secret_identity', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superheroes.City')),
                ('enemies', models.ManyToManyField(to='superheroes.Enemy')),
                ('powers', models.ManyToManyField(to='superheroes.Power')),
                ('date_of_death', superheroes.models.DefaultDate(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='powers',
            field=models.ManyToManyField(to='superheroes.Power'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'permissions': [('create_dataframe', 'Can Create Dataframe')]},
        ),
    ]
