# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 21:11
from __future__ import unicode_literals

from django.db import migrations
import superheroes.models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_auto_20171102_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='date_of_death',
            field=superheroes.models.DefaultDate(null=True),
        ),
    ]
