# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_superhero_date_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enemy',
            options={'permissions': [('create_dataframe', 'Can Create Dataframe')]},
        ),
    ]
