# Generated by Django 2.2.16 on 2020-10-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('place_of_birth', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
                ('tate_url', models.URLField()),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('date_text', models.CharField(max_length=64)),
                ('thumbnail_url', models.URLField()),
                ('tate_url', models.URLField()),
                ('uuid', models.UUIDField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tate_core.Artist')),
            ],
        ),
    ]
