# Generated by Django 2.2.16 on 2020-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tate_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='death_year',
            field=models.IntegerField(null=True),
        ),
    ]
