# Generated by Django 2.2.16 on 2020-10-25 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tate_core', '0002_auto_20201025_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
