# Generated by Django 2.2.16 on 2020-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tate_core', '0003_auto_20201025_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='tate_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
