# Generated by Django 3.1.2 on 2020-10-29 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tate_core', '0005_auto_20201025_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_year',
            field=models.IntegerField(help_text='Year the artist was born', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='death_year',
            field=models.IntegerField(help_text='Year the artist died', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this artist', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text="Artist's full name", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='place_of_birth',
            field=models.CharField(help_text="Location of artist's birth", max_length=256),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tate_url',
            field=models.URLField(help_text='Link to this artist at www.tate.org.uk', null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(help_text='Artist who created this artwork', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='tate_core.artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date_text',
            field=models.CharField(help_text='Date artwork was completed (if known)', max_length=64),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this artwork', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='tate_url',
            field=models.URLField(help_text='Link to a full image of this artwork at www.tate.org.uk'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='thumbnail_url',
            field=models.URLField(help_text='Link to a thumbnail of this artwork at www.tate.org.uk'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(default=None, help_text='Title of the artwork', max_length=512),
        ),
    ]
