# Generated by Django 3.1.3 on 2020-11-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(help_text='Title', max_length=8, null=True),
        ),
    ]
