# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='band',
            order_with_respect_to='genre',
        ),
    ]
