# Generated by Django 4.1 on 2022-08-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandmember',
            old_name='is_current',
            new_name='is_current_or_last',
        ),
    ]
