# Generated by Django 4.1 on 2022-08-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_rename_is_current_bandmember_is_current_or_last'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Artist',
        ),
    ]
