# Generated by Django 4.1 on 2022-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaf_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'loafs',
            },
        ),
    ]
