# Generated by Django 4.1 on 2022-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeasty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaf',
            name='rising_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
