# Generated by Django 4.1 on 2022-08-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeasty', '0002_loaf_rising_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loaf',
            table='loaves',
        ),
    ]
